name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: cd backend && npm install
      - name: Install frontend dependencies
        run: cd frontend && npm install
      - name: Check style
        run: cd frontend && npm run lint
      - name: Build
        run: cd frontend && npm run build  

      - name: Move dist folder to backend
        run: |
          rm -rf backend/dist
          mv frontend/dist backend/

      #- name: e2e tests
      #  uses: cypress-io/github-action@v5
      #  with:
      #    command: npm run test:e2e
      #    start: npm run start-prod
      #    wait-on: http://localhost:5000


